modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/sunny-verdant-leaves/verdant-sky/issues"
license = "MIT"

[[mods]]
modId = "verdant_sky"
version = "${version}"
displayName = "Verdant Sky"
authors = "Sunny Verdant Leaves"
description = '''
This is a Minecraft mod for the Verdant Sky modpack.
'''
logoFile = "logo.png"

[[dependencies.verdant_sky]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.verdant_sky]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.verdant_sky]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.10,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.verdant_sky]]
modId = "botania"
mandatory = true
versionRange = "[1.20.1-453,)"
ordering = "AFTER"
side = "BOTH"